##### Prefix #####
# C-b -> C-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

##### Basic #####
# Mouse ON
set -g mouse on
# History
set -g history-limit 10000
# indexを1始まり
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
# Hi-Color
set -g default-terminal "screen-256color"

##### Vi Style #####
setw -g mode-keys vi  #コピーモード
set -g status-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

#パネル移動
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

#パネルサイズ調整
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

# スクロール
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flug}" \
  "send-keys -M" \
  "copy-mode -e"

##### Window #####
bind | split-window -h
bind - split-window -v

##### Status bar #####
set -g status-position bottom
set -g status-left-length 30
set -g status-right-length 80
set -g status-left '#S '
set -g status-right '%Y-%m-%d %H:%M'

##### Reload #####
bind r source-file ~/.tmux.conf \; display "Reloaded!"

