# Mouse ON
set -g mouse on

# History
set -g history-limit 10000

# viコピーモード
setw -g mode-keys vi

# スクロール
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flug}" \
  "send-keys -M" \
  "copy-mode -e"

# indexを1始まり
set -g base-index 1
setw -g pane-base-index 1

# Reload
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Hi-Color
set -g default-terminal "screen-256color"
