add_newline = true

format = """
$username$hostname $directory $git_branch$git_status
$character
"""

right_format = """
$cmd_duration $time
"""
#$battery $cmd_duration $time

[username]
show_always = true
style_user = "bold green"
style_root = "bold red"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold yellow"
format = "[@$hostname]($style)"

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bold purple"
format = "[$symbol$branch]($style)"

[git_status]
style = "bold red"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold yellow)"


# == right format

[time]
disabled = false
time_format = "\uf017 %H:%M"
format = "[$time](bold cyan)"

[cmd_duration]
min_time = 1000
format = "[\uea86 $duration](yellow)"

[battery]
disabled = false

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 40
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"
